{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mcp-inspector.fullname" . }}
  labels:
    {{- include "mcp-inspector.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  port:
    targetPort: client
  to:
    kind: Service
    name: {{ include "mcp-inspector.fullname" . }}
    weight: 100
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
---
{{- if .Values.route.proxy.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mcp-inspector.fullname" . }}-proxy
  labels:
    {{- include "mcp-inspector.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.proxy.host }}
  host: {{ .Values.route.proxy.host }}
  {{- end }}
  port:
    targetPort: server
  to:
    kind: Service
    name: {{ include "mcp-inspector.fullname" . }}
    weight: 100
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
{{- end }}
